// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUQU7Z3qPVMaij5TXwD6UgawPb08GWTY0',
    appId: '1:1021697483187:web:10b9b82cb6383a6deb6bc6',
    messagingSenderId: '1021697483187',
    projectId: 'vobpl-attendance',
    authDomain: 'vobpl-attendance.firebaseapp.com',
    storageBucket: 'vobpl-attendance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgUjB3lfi9Evedj67soPtRonvbv8NkW6U',
    appId: '1:1021697483187:android:d0f51e8a4329e127eb6bc6',
    messagingSenderId: '1021697483187',
    projectId: 'vobpl-attendance',
    storageBucket: 'vobpl-attendance.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdQaOmHGowxgGQTpniikRLBFrmawTECio',
    appId: '1:559999176099:ios:c3467091682e9fa443de16',
    messagingSenderId: '559999176099',
    projectId: 'vobpl-inventory-system',
    storageBucket: 'vobpl-inventory-system.firebasestorage.app',
    iosBundleId: 'vobplsmart.in.vobplAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdQaOmHGowxgGQTpniikRLBFrmawTECio',
    appId: '1:559999176099:ios:c3467091682e9fa443de16',
    messagingSenderId: '559999176099',
    projectId: 'vobpl-inventory-system',
    storageBucket: 'vobpl-inventory-system.firebasestorage.app',
    iosBundleId: 'vobplsmart.in.vobplAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPbTAviM763nnSNZ0ou22k26taCqIUx8M',
    appId: '1:559999176099:web:7a81ed072380e27543de16',
    messagingSenderId: '559999176099',
    projectId: 'vobpl-inventory-system',
    authDomain: 'vobpl-inventory-system.firebaseapp.com',
    storageBucket: 'vobpl-inventory-system.firebasestorage.app',
    measurementId: 'G-SSBZD0589H',
  );
}
